declare module y3.Const
{
    const enum AbilityEventType
    {
        ['ABILITY_CS_START'] = "ET_ABILITY_CS_START",
        ['ABILITY_PS_START'] = "ET_ABILITY_PS_START",
        ['ABILITY_PS_END'] = "ET_ABILITY_PS_END",
        ['ABILITY_SP_END'] = "ET_ABILITY_SP_END",
        ['ABILITY_CST_END'] = "ET_ABILITY_CST_END",
        ['ABILITY_BS_END'] = "ET_ABILITY_BS_END",
        ['ABILITY_PS_INTERRUPT'] = "ET_ABILITY_PS_INTERRUPT",
        ['ABILITY_SP_INTERRUPT'] = "ET_ABILITY_SP_INTERRUPT",
        ['ABILITY_CST_INTERRUPT'] = "ET_ABILITY_CST_INTERRUPT",
        ['ABILITY_END'] = "ET_ABILITY_END",
        ['ABILITY_OBTAIN'] = "ET_ABILITY_OBTAIN",
        ['ABILITY_LOSE'] = "ET_ABILITY_LOSE",
        ['ABILITY_UPGRADE'] = "ET_ABILITY_PLUS_POINT",
        ['ABILITY_LEVEL_CHANGED'] = "ET_ABILITY_UPGRADE",
        ['ABILITY_CD_END'] = "ET_ABILITY_CD_END",
        ['ABILITY_SWITCH'] = "ET_ABILITY_SWITCH",
    }
}