declare module y3.Const
{
    const enum ModifierEventType
    {
        ['OBTAIN_MODIFIER'] = "ET_OBTAIN_MODIFIER",
        ['LOSS_MODIFIER'] = "ET_LOSS_MODIFIER",
        ['MODIFIER_CYCLE_TRIGGER'] = "ET_MODIFIER_CYCLE_TRIGGER",
        ['MODIFIER_LAYER_CHANGE'] = "ET_MODIFIER_LAYER_CHANGE",
        ['MODIFIER_GET_BEFORE_CREATE'] = "ET_MODIFIER_GET_BEFORE_CREATE",
        ['MODIFIER_BE_COVERED'] = "ET_MODIFIER_BE_COVERED",
        ['MODIFIER_ADDTION'] = "ET_MODIFIER_ADDTION",
    }
}